using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace CapaComun
{
    /*
     Administracion de multiples idiomas (Unidad 5 - Modulo de Seguridad).
     Clase comun a todas las capas: centraliza las traducciones en una tabla
     de recursos por idioma y permite cambiar el idioma activo en tiempo de ejecucion.
    */
    public static class Idioma
    {
        public const string Espanol = "es";
        public const string Ingles = "en";
        public const string Portugues = "pt";

        // Idioma activo (por defecto Espanol)
        public static string Actual { get; private set; } = Espanol;

        // Diccionario: idioma -> (clave -> texto)
        private static readonly Dictionary<string, Dictionary<string, string>> recursos =
            new Dictionary<string, Dictionary<string, string>>
        {
            [Espanol] = new Dictionary<string, string>
            {
                ["Mantenimiento"] = "Mantenimiento",
                ["Usuarios"] = "Usuarios",
                ["CambioPassword"] = "Cambio de Password",
                ["MantenimientoUsuarios"] = "Mantenimiento de Usuarios",
                ["Ubicaciones"] = "Ubicaciones",
                ["Salir"] = "Salir",
                ["Facturacion"] = "Facturación",
                ["Ventas"] = "Ventas",
                ["Stock"] = "Stock",
                ["Administracion"] = "Administración",
                ["Registros"] = "Registros",
                ["Bitacora"] = "Bitácora",
                ["GestionUsuarios"] = "Registrar usuario",
                ["RegistrarUsuario"] = "Registrar usuario",
                ["RegistrarUsuario_Titulo"] = "Registro de usuario del sistema",
                ["RegistrarUsuario_Personal"] = "Datos personales",
                ["RegistrarUsuario_Acceso"] = "Usuario del sistema",
                ["Apellido"] = "Apellido",
                ["Nombres"] = "Nombres",
                ["TipoDoc"] = "Tipo doc.",
                ["NroDoc"] = "Nro. doc.",
                ["Correo"] = "Correo",
                ["Localidad"] = "Localidad",
                ["UsuarioLogin"] = "Usuario",
                ["Password"] = "Contraseña",
                ["ConfirmarPassword"] = "Confirmar contraseña",
                ["Cargo"] = "Cargo",
                ["Btn_Registrar"] = "Registrar",
                ["Btn_Limpiar"] = "Limpiar",
                ["Msg_UsuarioRegistrado"] = "Usuario registrado correctamente.",
                ["Msg_CompletarApellidoNombre"] = "Ingrese apellido y nombres.",
                ["Msg_NroDocInvalido"] = "El número de documento no es válido.",
                ["Msg_SeleccioneTipoDoc"] = "Seleccione el tipo de documento.",
                ["Msg_DocumentoExiste"] = "Ya existe una persona con ese documento.",
                ["Msg_CorreoInvalido"] = "El correo electrónico no es válido.",
                ["Msg_CompletarUsuario"] = "Ingrese el nombre de usuario.",
                ["Msg_UsuarioExiste"] = "Ese nombre de usuario ya está en uso.",
                ["Msg_PasswordCorta"] = "La contraseña debe tener al menos 3 caracteres.",
                ["Msg_PasswordNoCoincide"] = "Las contraseñas no coinciden.",
                ["Msg_ErrorTitulo"] = "Error",
                ["Msg_PersonalSinLogin"] = "Personal guardado. Para que pueda ingresar al sistema use Administración → Registrar usuario.",
                ["Msg_PersonaExisteCrearUsuario"] = "Esa persona ya está en Personal. ¿Desea crear solo el usuario de acceso (login y rol)?",
                ["Msg_PersonaYaTieneUsuario"] = "Esa persona ya tiene un usuario de acceso asignado.",
                ["GestionPersonal"] = "Gestión de Personal",
                ["Idioma"] = "Idioma",
                ["Sesion"] = "Sesión de",

                ["ABMProvincia_Titulo"] = "Administración de Provincias",
                ["Provincia_Nombre"] = "Nombre de la provincia",
                ["Provincia_Id"] = "Identificación de la provincia:",
                ["Btn_Agregar"] = "Agregar",
                ["Btn_Modificar"] = "Modificar",
                ["Btn_Eliminar"] = "Eliminar",
                ["Btn_Atras"] = "Atrás",
                ["Msg_GuardadoError"] = "No se guardaron los datos por:",
                ["Msg_ConfirmEliminar"] = "¿Está seguro de ELIMINAR el registro seleccionado?",
                ["Msg_ConfirmEliminarTitulo"] = "ELIMINAR",
                ["Msg_SeleccioneRegistro"] = "Debe seleccionar un registro de la lista.",
                ["Msg_NombreVacio"] = "Debe ingresar el nombre de la provincia.",

                ["Btn_Guardar"] = "Guardar",
                ["Btn_GuardarCambios"] = "Guardar cambios",
                ["Btn_Cancelar"] = "Cancelar",
                ["Btn_Salir"] = "Salir",
                ["Btn_Cobrar"] = "Cobrar",
                ["Compras"] = "Compras",
                ["Proveedores"] = "Proveedores",
                ["Productos"] = "Productos",
                ["Menu"] = "Menú",
                ["Pedidos"] = "Pedidos / Facturación",
                ["Msg_CampoObligatorio"] = "Debe completar los campos obligatorios.",
                ["Msg_SeleccioneProveedor"] = "Debe seleccionar un proveedor.",
                ["Msg_SeleccioneProducto"] = "Debe seleccionar un producto.",
                ["Msg_SeleccioneMenu"] = "Debe seleccionar un menú.",
                ["Msg_CantidadInvalida"] = "La cantidad ingresada no es válida.",
                ["Msg_PrecioInvalido"] = "El precio ingresado no es válido.",
                ["Msg_TiempoInvalido"] = "El tiempo de preparación no es válido.",
                ["Msg_ConfirmCobrar"] = "¿Confirma el cobro del pedido seleccionado?",
                ["Nombre"] = "Nombre",
                ["RazonSocial"] = "Razón Social",
                ["Categoria"] = "Categoría",
                ["CUIT"] = "CUIT",
                ["CertificadoAfip"] = "Certificado AFIP",
                ["Direccion"] = "Dirección",
                ["Email"] = "Email",
                ["Telefono"] = "Teléfono",
                ["Descripcion"] = "Descripción",
                ["Marca"] = "Marca",
                ["Medida"] = "Medida",
                ["Proveedor"] = "Proveedor",
                ["Producto"] = "Producto",
                ["NumeroLote"] = "Número de lote",
                ["Cantidad"] = "Cantidad",
                ["Vencimiento"] = "Vencimiento",
                ["Precio"] = "Precio",
                ["Ingredientes"] = "Ingredientes",
                ["Popularidad"] = "Popularidad",
                ["Region"] = "Región",
                ["Temporada"] = "Temporada",
                ["TipoEvento"] = "Tipo de evento",
                ["Tiempo"] = "Tiempo (min)",
                ["Cliente"] = "Cliente",
                ["FormaPago"] = "Forma de pago",
                ["Estado"] = "Estado",
                ["PrecioTotal"] = "Precio total",
                ["Fecha"] = "Fecha",
                ["Instrucciones"] = "Instrucciones",
                ["Prov_Titulo"] = "Gestión de Proveedores",
                ["Prod_Titulo"] = "Gestión de Productos",
                ["Stock_Titulo"] = "Gestión de Stock",
                ["Menu_Titulo"] = "Gestión de Menú",
                ["Fact_Titulo"] = "Pedidos y Facturación",
                ["Msg_SinPermiso"] = "No tiene permisos para acceder a esta función.",
                ["Rol"] = "Rol",
                ["AsignarRol"] = "Asignar rol",
                ["AsignarRol_Titulo"] = "Asignación de roles",
                ["RolUsuario"] = "Rol del usuario",
                ["Btn_GuardarRol"] = "Guardar rol",
                ["Msg_SeleccioneUsuario"] = "Seleccione un usuario de la lista.",
                ["Msg_SeleccioneRol"] = "Seleccione un rol.",
                ["Msg_RolGuardado"] = "Rol asignado correctamente. El usuario debe volver a ingresar.",
                ["Bitacora_Titulo"] = "Consulta de bitácora",
                ["Bitacora_FiltroEvento"] = "Evento",
                ["Bitacora_FiltroUsuario"] = "Usuario",
                ["Bitacora_FechaDesde"] = "Fecha desde",
                ["Bitacora_FechaHasta"] = "Fecha hasta",
                ["Bitacora_Filtrar"] = "Filtrar",
                ["Bitacora_FechaInvalida"] = "La fecha desde no puede ser mayor que la fecha hasta.",
                ["Bitacora_VerDetalle"] = "▼ Ver detalle completo",
                ["Bitacora_OcultarDetalle"] = "▲ Ocultar detalle",
                ["Bitacora_DetalleTitulo"] = "Detalle del registro seleccionado",
                ["Estadisticas"] = "Estadísticas",
                ["Estadisticas_Titulo"] = "Estadísticas de ventas",
                ["Estadisticas_Resumen"] = "Pedidos por estado",
                ["Estadisticas_Hoy"] = "Pedidos del día"
            },
            [Ingles] = new Dictionary<string, string>
            {
                ["Mantenimiento"] = "Maintenance",
                ["Usuarios"] = "Users",
                ["CambioPassword"] = "Change Password",
                ["MantenimientoUsuarios"] = "Users Maintenance",
                ["Ubicaciones"] = "Locations",
                ["Salir"] = "Exit",
                ["Facturacion"] = "Billing",
                ["Ventas"] = "Sales",
                ["Stock"] = "Stock",
                ["Administracion"] = "Administration",
                ["Registros"] = "Logs",
                ["Bitacora"] = "Audit log",
                ["GestionUsuarios"] = "Register user",
                ["RegistrarUsuario"] = "Register user",
                ["RegistrarUsuario_Titulo"] = "System user registration",
                ["RegistrarUsuario_Personal"] = "Personal data",
                ["RegistrarUsuario_Acceso"] = "System account",
                ["Apellido"] = "Last name",
                ["Nombres"] = "First name",
                ["TipoDoc"] = "ID type",
                ["NroDoc"] = "ID number",
                ["Correo"] = "Email",
                ["Localidad"] = "City",
                ["UsuarioLogin"] = "Username",
                ["Password"] = "Password",
                ["ConfirmarPassword"] = "Confirm password",
                ["Cargo"] = "Job title",
                ["Btn_Registrar"] = "Register",
                ["Btn_Limpiar"] = "Clear",
                ["Msg_UsuarioRegistrado"] = "User registered successfully.",
                ["Msg_CompletarApellidoNombre"] = "Enter last name and first name.",
                ["Msg_NroDocInvalido"] = "The ID number is not valid.",
                ["Msg_SeleccioneTipoDoc"] = "Select an ID type.",
                ["Msg_DocumentoExiste"] = "A person with that ID already exists.",
                ["Msg_CorreoInvalido"] = "The email address is not valid.",
                ["Msg_CompletarUsuario"] = "Enter a username.",
                ["Msg_UsuarioExiste"] = "That username is already in use.",
                ["Msg_PasswordCorta"] = "Password must be at least 3 characters.",
                ["Msg_PasswordNoCoincide"] = "Passwords do not match.",
                ["Msg_ErrorTitulo"] = "Error",
                ["Msg_PersonalSinLogin"] = "Staff saved. To allow system login use Administration → Register user.",
                ["Msg_PersonaExisteCrearUsuario"] = "This person is already in Staff. Create only the access account (login and role)?",
                ["Msg_PersonaYaTieneUsuario"] = "This person already has a system access account.",
                ["GestionPersonal"] = "Staff Management",
                ["Idioma"] = "Language",
                ["Sesion"] = "Session of",

                ["ABMProvincia_Titulo"] = "Provinces Management",
                ["Provincia_Nombre"] = "Province name",
                ["Provincia_Id"] = "Province id:",
                ["Btn_Agregar"] = "Add",
                ["Btn_Modificar"] = "Edit",
                ["Btn_Eliminar"] = "Delete",
                ["Btn_Atras"] = "Back",
                ["Msg_GuardadoError"] = "Data could not be saved because:",
                ["Msg_ConfirmEliminar"] = "Are you sure you want to DELETE the selected record?",
                ["Msg_ConfirmEliminarTitulo"] = "DELETE",
                ["Msg_SeleccioneRegistro"] = "You must select a record from the list.",
                ["Msg_NombreVacio"] = "You must enter the province name.",

                ["Btn_Guardar"] = "Save",
                ["Btn_GuardarCambios"] = "Save changes",
                ["Btn_Cancelar"] = "Cancel",
                ["Btn_Salir"] = "Exit",
                ["Btn_Cobrar"] = "Charge",
                ["Compras"] = "Purchases",
                ["Proveedores"] = "Suppliers",
                ["Productos"] = "Products",
                ["Menu"] = "Menu",
                ["Pedidos"] = "Orders / Billing",
                ["Msg_CampoObligatorio"] = "You must complete the required fields.",
                ["Msg_SeleccioneProveedor"] = "You must select a supplier.",
                ["Msg_SeleccioneProducto"] = "You must select a product.",
                ["Msg_SeleccioneMenu"] = "You must select a menu.",
                ["Msg_CantidadInvalida"] = "The entered quantity is not valid.",
                ["Msg_PrecioInvalido"] = "The entered price is not valid.",
                ["Msg_TiempoInvalido"] = "The preparation time is not valid.",
                ["Msg_ConfirmCobrar"] = "Do you confirm charging the selected order?",
                ["Nombre"] = "Name",
                ["RazonSocial"] = "Business name",
                ["Categoria"] = "Category",
                ["CUIT"] = "Tax ID",
                ["CertificadoAfip"] = "Tax certificate",
                ["Direccion"] = "Address",
                ["Email"] = "Email",
                ["Telefono"] = "Phone",
                ["Descripcion"] = "Description",
                ["Marca"] = "Brand",
                ["Medida"] = "Unit",
                ["Proveedor"] = "Supplier",
                ["Producto"] = "Product",
                ["NumeroLote"] = "Batch number",
                ["Cantidad"] = "Quantity",
                ["Vencimiento"] = "Expiration",
                ["Precio"] = "Price",
                ["Ingredientes"] = "Ingredients",
                ["Popularidad"] = "Popularity",
                ["Region"] = "Region",
                ["Temporada"] = "Season",
                ["TipoEvento"] = "Event type",
                ["Tiempo"] = "Time (min)",
                ["Cliente"] = "Customer",
                ["FormaPago"] = "Payment method",
                ["Estado"] = "Status",
                ["PrecioTotal"] = "Total price",
                ["Fecha"] = "Date",
                ["Instrucciones"] = "Instructions",
                ["Prov_Titulo"] = "Suppliers Management",
                ["Prod_Titulo"] = "Products Management",
                ["Stock_Titulo"] = "Stock Management",
                ["Menu_Titulo"] = "Menu Management",
                ["Fact_Titulo"] = "Orders and Billing",
                ["Msg_SinPermiso"] = "You do not have permission to access this function.",
                ["Rol"] = "Role",
                ["AsignarRol"] = "Assign role",
                ["AsignarRol_Titulo"] = "Role assignment",
                ["RolUsuario"] = "User role",
                ["Btn_GuardarRol"] = "Save role",
                ["Msg_SeleccioneUsuario"] = "Select a user from the list.",
                ["Msg_SeleccioneRol"] = "Select a role.",
                ["Msg_RolGuardado"] = "Role saved. The user must log in again.",
                ["Bitacora_Titulo"] = "Audit log",
                ["Bitacora_FiltroEvento"] = "Event",
                ["Bitacora_FiltroUsuario"] = "User",
                ["Bitacora_FechaDesde"] = "Date from",
                ["Bitacora_FechaHasta"] = "Date to",
                ["Bitacora_Filtrar"] = "Filter",
                ["Bitacora_FechaInvalida"] = "Start date cannot be after end date.",
                ["Bitacora_VerDetalle"] = "▼ View full detail",
                ["Bitacora_OcultarDetalle"] = "▲ Hide detail",
                ["Bitacora_DetalleTitulo"] = "Selected record detail",
                ["Estadisticas"] = "Statistics",
                ["Estadisticas_Titulo"] = "Sales statistics",
                ["Estadisticas_Resumen"] = "Orders by status",
                ["Estadisticas_Hoy"] = "Today's orders"
            },
            [Portugues] = new Dictionary<string, string>
            {
                ["Mantenimiento"] = "Manutenção",
                ["Usuarios"] = "Usuários",
                ["CambioPassword"] = "Alterar Senha",
                ["MantenimientoUsuarios"] = "Manutenção de Usuários",
                ["Ubicaciones"] = "Localizações",
                ["Salir"] = "Sair",
                ["Facturacion"] = "Faturamento",
                ["Ventas"] = "Vendas",
                ["Stock"] = "Estoque",
                ["Administracion"] = "Administração",
                ["Registros"] = "Registros",
                ["Bitacora"] = "Auditoria",
                ["GestionUsuarios"] = "Registrar usuário",
                ["RegistrarUsuario"] = "Registrar usuário",
                ["RegistrarUsuario_Titulo"] = "Cadastro de usuário do sistema",
                ["RegistrarUsuario_Personal"] = "Dados pessoais",
                ["RegistrarUsuario_Acceso"] = "Usuário do sistema",
                ["Apellido"] = "Sobrenome",
                ["Nombres"] = "Nomes",
                ["TipoDoc"] = "Tipo doc.",
                ["NroDoc"] = "Nro. doc.",
                ["Correo"] = "E-mail",
                ["Localidad"] = "Localidade",
                ["UsuarioLogin"] = "Usuário",
                ["Password"] = "Senha",
                ["ConfirmarPassword"] = "Confirmar senha",
                ["Cargo"] = "Cargo",
                ["Btn_Registrar"] = "Registrar",
                ["Btn_Limpiar"] = "Limpar",
                ["Msg_UsuarioRegistrado"] = "Usuário registrado com sucesso.",
                ["Msg_CompletarApellidoNombre"] = "Informe sobrenome e nomes.",
                ["Msg_NroDocInvalido"] = "O número do documento não é válido.",
                ["Msg_SeleccioneTipoDoc"] = "Selecione o tipo de documento.",
                ["Msg_DocumentoExiste"] = "Já existe uma pessoa com esse documento.",
                ["Msg_CorreoInvalido"] = "O e-mail não é válido.",
                ["Msg_CompletarUsuario"] = "Informe o nome de usuário.",
                ["Msg_UsuarioExiste"] = "Esse nome de usuário já está em uso.",
                ["Msg_PasswordCorta"] = "A senha deve ter pelo menos 3 caracteres.",
                ["Msg_PasswordNoCoincide"] = "As senhas não coincidem.",
                ["Msg_ErrorTitulo"] = "Erro",
                ["Msg_PersonalSinLogin"] = "Pessoal salvo. Para permitir login use Administração → Registrar usuário.",
                ["Msg_PersonaExisteCrearUsuario"] = "Essa pessoa já está no cadastro. Criar apenas o usuário de acesso (login e papel)?",
                ["Msg_PersonaYaTieneUsuario"] = "Essa pessoa já possui usuário de acesso.",
                ["GestionPersonal"] = "Gestão de Pessoal",
                ["Idioma"] = "Idioma",
                ["Sesion"] = "Sessão de",

                ["ABMProvincia_Titulo"] = "Administração de Províncias",
                ["Provincia_Nombre"] = "Nome da província",
                ["Provincia_Id"] = "Identificação da província:",
                ["Btn_Agregar"] = "Adicionar",
                ["Btn_Modificar"] = "Modificar",
                ["Btn_Eliminar"] = "Excluir",
                ["Btn_Atras"] = "Voltar",
                ["Msg_GuardadoError"] = "Os dados não foram salvos porque:",
                ["Msg_ConfirmEliminar"] = "Tem certeza de que deseja EXCLUIR o registro selecionado?",
                ["Msg_ConfirmEliminarTitulo"] = "EXCLUIR",
                ["Msg_SeleccioneRegistro"] = "Você deve selecionar um registro da lista.",
                ["Msg_NombreVacio"] = "Você deve informar o nome da província.",

                ["Btn_Guardar"] = "Salvar",
                ["Btn_GuardarCambios"] = "Salvar alterações",
                ["Btn_Cancelar"] = "Cancelar",
                ["Btn_Salir"] = "Sair",
                ["Btn_Cobrar"] = "Cobrar",
                ["Compras"] = "Compras",
                ["Proveedores"] = "Fornecedores",
                ["Productos"] = "Produtos",
                ["Menu"] = "Cardápio",
                ["Pedidos"] = "Pedidos / Faturamento",
                ["Msg_CampoObligatorio"] = "Você deve preencher os campos obrigatórios.",
                ["Msg_SeleccioneProveedor"] = "Você deve selecionar um fornecedor.",
                ["Msg_SeleccioneProducto"] = "Você deve selecionar um produto.",
                ["Msg_SeleccioneMenu"] = "Você deve selecionar um cardápio.",
                ["Msg_CantidadInvalida"] = "A quantidade informada não é válida.",
                ["Msg_PrecioInvalido"] = "O preço informado não é válido.",
                ["Msg_TiempoInvalido"] = "O tempo de preparo não é válido.",
                ["Msg_ConfirmCobrar"] = "Confirma a cobrança do pedido selecionado?",
                ["Nombre"] = "Nome",
                ["RazonSocial"] = "Razão social",
                ["Categoria"] = "Categoria",
                ["CUIT"] = "CNPJ",
                ["CertificadoAfip"] = "Certificado fiscal",
                ["Direccion"] = "Endereço",
                ["Email"] = "Email",
                ["Telefono"] = "Telefone",
                ["Descripcion"] = "Descrição",
                ["Marca"] = "Marca",
                ["Medida"] = "Medida",
                ["Proveedor"] = "Fornecedor",
                ["Producto"] = "Produto",
                ["NumeroLote"] = "Número do lote",
                ["Cantidad"] = "Quantidade",
                ["Vencimiento"] = "Vencimento",
                ["Precio"] = "Preço",
                ["Ingredientes"] = "Ingredientes",
                ["Popularidad"] = "Popularidade",
                ["Region"] = "Região",
                ["Temporada"] = "Temporada",
                ["TipoEvento"] = "Tipo de evento",
                ["Tiempo"] = "Tempo (min)",
                ["Cliente"] = "Cliente",
                ["FormaPago"] = "Forma de pagamento",
                ["Estado"] = "Estado",
                ["PrecioTotal"] = "Preço total",
                ["Fecha"] = "Data",
                ["Instrucciones"] = "Instruções",
                ["Prov_Titulo"] = "Gestão de Fornecedores",
                ["Prod_Titulo"] = "Gestão de Produtos",
                ["Stock_Titulo"] = "Gestão de Estoque",
                ["Menu_Titulo"] = "Gestão de Cardápio",
                ["Fact_Titulo"] = "Pedidos e Faturamento",
                ["Msg_SinPermiso"] = "Você não tem permissão para acessar esta função.",
                ["Rol"] = "Papel",
                ["AsignarRol"] = "Atribuir papel",
                ["AsignarRol_Titulo"] = "Atribuição de papéis",
                ["RolUsuario"] = "Papel do usuário",
                ["Btn_GuardarRol"] = "Salvar papel",
                ["Msg_SeleccioneUsuario"] = "Selecione um usuário da lista.",
                ["Msg_SeleccioneRol"] = "Selecione um papel.",
                ["Msg_RolGuardado"] = "Papel atribuído. O usuário deve entrar novamente.",
                ["Bitacora_Titulo"] = "Consulta de auditoria",
                ["Bitacora_FiltroEvento"] = "Evento",
                ["Bitacora_FiltroUsuario"] = "Usuário",
                ["Bitacora_FechaDesde"] = "Data de",
                ["Bitacora_FechaHasta"] = "Data até",
                ["Bitacora_Filtrar"] = "Filtrar",
                ["Bitacora_FechaInvalida"] = "A data inicial não pode ser maior que a final.",
                ["Bitacora_VerDetalle"] = "▼ Ver detalhe completo",
                ["Bitacora_OcultarDetalle"] = "▲ Ocultar detalhe",
                ["Bitacora_DetalleTitulo"] = "Detalhe do registro selecionado",
                ["Estadisticas"] = "Estatísticas",
                ["Estadisticas_Titulo"] = "Estatísticas de vendas",
                ["Estadisticas_Resumen"] = "Pedidos por estado",
                ["Estadisticas_Hoy"] = "Pedidos do dia"
            }
        };

        // Cambia el idioma activo y la cultura del hilo actual
        public static void Establecer(string idioma)
        {
            if (!recursos.ContainsKey(idioma))
            {
                idioma = Espanol;
            }
            Actual = idioma;

            CultureInfo cultura = new CultureInfo(idioma);
            Thread.CurrentThread.CurrentCulture = cultura;
            Thread.CurrentThread.CurrentUICulture = cultura;
        }

        // Devuelve el texto traducido para la clave en el idioma activo.
        // Si no existe la clave, devuelve la propia clave para evitar errores.
        public static string Texto(string clave)
        {
            if (recursos.TryGetValue(Actual, out var tabla) &&
                tabla.TryGetValue(clave, out var texto))
            {
                return texto;
            }
            return clave;
        }
    }
}
